{
  "uid" : "107f225632dc9a70",
  "name" : "Test_login_BU.test_tc001",
  "title" : "Test tc 001",
  "time" : {
    "start" : 1461245618024,
    "stop" : 1461245629653,
    "duration" : 11629
  },
  "summary" : {
    "attachments" : 1,
    "steps" : 0
  },
  "failure" : {
    "message" : "AssertionError: assert False",
    "stackTrace" : "self = <com.workspace.project01.module.front_back.login_page.test_login_BU.Test_login_BU instance at 0x03461F58>\n\n    @allure.story('Functional')\n    @pytest.allure.severity(pytest.allure.severity_level.CRITICAL)\n    def test_tc001(self):\n        allure.attach('my attach', 'Hello, World')\n        self.logInfo(\"Verify user can't login with empty username and password\")\n        self.logInfo(\"1. Leave username and password blank\")\n        self.logInfo(\"2. Click Login button\")\n        self.loginPage().login(\"\", \"\")\n    \n        self.logInfo(\"3. Verify the 'Empty password not allowed' error message is displayed\")\n>       self.loginPage().checkErrorMessageDisplayed(self.UsernameAndPasswordNotMacthMessage)\n\nmodule\\front_back\\login_page\\test_login_BU.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nactions\\pages\\Login.py:32: in checkErrorMessageDisplayed\n    \"The error message '%s' is displayed instead of '%s'\" % (messageContent, message))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <com.workspace.project01.actions.pages.Login.Login instance at 0x03461D78>\nexpression = False\npassMsg = \"The error message 'Username and password do not match or you do not have an account yet.' is displayed\"\nfailMsg = \"The error message 'Empty password not allowed' is displayed instead of 'Username and password do not match or you do not have an account yet.'\"\nisBug = False\n\n    def verifyTrue(self, expression, passMsg, failMsg, isBug = False):\n        if expression == True:\n            self.logPass(passMsg)\n            assert expression\n        else:\n            self.logFail(failMsg)\n            if (isBug == False):\n>               assert expression\nE               assert False\n\nactions\\AbstractPage.py:297: AssertionError"
  },
  "description" : {
    "value" : "\nCreated on Apr 15, 2016\n\n@author: ZinhVcoin\n",
    "type" : "TEXT"
  },
  "severity" : "CRITICAL",
  "status" : "BROKEN",
  "testId" : null,
  "suite" : {
    "uid" : "7b6e6b834b0fad77",
    "name" : "com.workspace.project01.module.front_back.login_page.test_login_BU",
    "title" : "Test login BU"
  },
  "steps" : [ ],
  "attachments" : [ {
    "title" : "my attach",
    "source" : "0335860f-6469-4aad-a9c2-5a9b3474991f-attachment.txt",
    "type" : "text/plain",
    "size" : 12,
    "uid" : "6f6492686c2d082a"
  } ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Login"
  }, {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "thread",
    "value" : "5764-MainThread"
  }, {
    "name" : "story",
    "value" : "Functional"
  }, {
    "name" : "host",
    "value" : "ZinhVcoin-PC"
  }, {
    "name" : "suite-name",
    "value" : "com.workspace.project01.module.front_back.login_page.test_login_BU"
  } ],
  "parameters" : [ ]
}