{
  "uid" : "5b79da29c4b0da92",
  "name" : "Test_login_BU.test_tc002",
  "title" : "Test tc 002",
  "time" : {
    "start" : 1461242789603,
    "stop" : 1461242791290,
    "duration" : 1687
  },
  "summary" : {
    "attachments" : 0,
    "steps" : 0
  },
  "failure" : {
    "message" : "AssertionError: assert False",
    "stackTrace" : "self = <com.workspace.project01.module.front_back.login_page.test_login_BU.Test_login_BU instance at 0x034499E0>\n\n    @allure.story('Functional')\n    @pytest.allure.severity(pytest.allure.severity_level.CRITICAL)\n    def test_tc002(self):\n    #         allure.attach('my attach', 'Hello, World')\n        self.logInfo(\"Verify user can't login with empty password\")\n        self.logInfo(\"1. Enter username\")\n        self.logInfo(\"2. Leave password blank\")\n        self.logInfo(\"3. Click Login button\")\n        self.loginPage().login(self.cfValidUsername, \"\")\n    \n        self.logInfo(\"3. Verify the 'Username and password do not match or you do not have an account yet.' error message is displayed\")\n>       self.loginPage().checkErrorMessageDisplayed(self.UsernameAndPasswordNotMacthMessage)\n\nmodule\\front_back\\login_page\\test_login_BU.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nactions\\pages\\Login.py:32: in checkErrorMessageDisplayed\n    \"The error message '%s' is displayed instead of '%s'\" % (messageContent, message))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <com.workspace.project01.actions.pages.Login.Login instance at 0x03435530>\nexpression = False\npassMsg = \"The error message 'Username and password do not match or you do not have an account yet.' is displayed\"\nfailMsg = \"The error message 'Empty password not allowed' is displayed instead of 'Username and password do not match or you do not have an account yet.'\"\n\n    def verifyTrue(self, expression, passMsg, failMsg):\n    #         try:\n            if expression == True:\n                self.logPass(passMsg)\n            else:\n                self.logFail(failMsg)\n    \n>           assert expression\nE           assert False\n\nactions\\AbstractPage.py:297: AssertionError"
  },
  "description" : {
    "value" : "\nCreated on Apr 15, 2016\n\n@author: ZinhVcoin\n",
    "type" : "TEXT"
  },
  "severity" : "CRITICAL",
  "status" : "FAILED",
  "testId" : null,
  "suite" : {
    "uid" : "41259410ad3ece9c",
    "name" : "com.workspace.project01.module.front_back.login_page.test_login_BU",
    "title" : "Test login BU"
  },
  "steps" : [ ],
  "attachments" : [ ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Login"
  }, {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "thread",
    "value" : "6260-MainThread"
  }, {
    "name" : "story",
    "value" : "Functional"
  }, {
    "name" : "host",
    "value" : "ZinhVcoin-PC"
  }, {
    "name" : "suite-name",
    "value" : "com.workspace.project01.module.front_back.login_page.test_login_BU"
  } ],
  "parameters" : [ ]
}