{
  "uid" : "6cb84908efa0f50",
  "name" : "test_long_stacktrace",
  "title" : "Test long stacktrace",
  "time" : {
    "start" : 1460562487592,
    "stop" : 1460562487601,
    "duration" : 9
  },
  "summary" : {
    "attachments" : 0,
    "steps" : 0
  },
  "failure" : {
    "message" : "RuntimeError: I am a failure reason",
    "stackTrace" : "def test_long_stacktrace():\n>       a_func('I am a failure reason')\n\ndemo\\test_basic_examples.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ndemo\\test_basic_examples.py:40: in a_func\n    return b_func(x)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nx = 'I am a failure reason'\n\n    def b_func(x):\n>       raise RuntimeError(x)\nE       RuntimeError: I am a failure reason\n\ndemo\\test_basic_examples.py:44: RuntimeError"
  },
  "description" : {
    "value" : "\nThese tests show some attachment examples\n\nCreated on Oct 18, 2013\n\n@author: pupssman\n",
    "type" : "TEXT"
  },
  "severity" : "NORMAL",
  "status" : "FAILED",
  "testId" : null,
  "suite" : {
    "uid" : "9ee7c1bbbc59433f",
    "name" : "demo.test_attaches",
    "title" : "Test attaches"
  },
  "steps" : [ ],
  "attachments" : [ ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "suite-name",
    "value" : "demo.test_attaches"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "host",
    "value" : "ZinhVcoin-PC"
  }, {
    "name" : "thread",
    "value" : "844-MainThread"
  } ],
  "parameters" : [ ]
}